name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g vsce

      - name: Run tests
        run: npm test

      - name: Package extension
        run: vsce package

      - name: Publish extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: vsce publish
